---
title: "Curriculum Vitae"
---

## Education

### Ph.D. in Mathematics

**POSTECH, Korea**  
February 2014

**Adviser:** Professor Jihun Park  
**Thesis:** *Log canonical thresholds of complete intersection log del Pezzo surfaces*

### B.A. in Mathematics

**Inha University, Korea**  
February 2005

**Award:** Summa Cum Laude from the College of Natural Sciences

## Employment

### CMC Fellow

**June E. Huh Center for Mathematical Challenges, Korea Institute for Advanced Study**  
September 2023 -- Present

### Research Professor

**Department of Mathematics, Yonsei University**  
September 2020 -- August 2023

### Research Professor

**Mathematics, Sungkyunkwan University**  
May 2019 -- August 2020

### Postdoctoral Researcher

**Research Institute of Mathematics, Seoul National University**  
March 2019 -- April 2019

### Postdoctoral Researcher

**SNU Mathematical Sciences Division for Creative Human Resources Development**  
March 2017 -- February 2019

### Postdoctoral Researcher

**Research Institute of Mathematics, Seoul National University**  
March 2014 -- February 2017
